package view;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Társila
 */
public class TelaDescricaoProblema extends javax.swing.JFrame {

    public TelaDescricaoProblema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagem = new javax.swing.JLabel();
        descricaoProblema = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problema do Transporte");
        setFont(new java.awt.Font("Adobe Arabic", 0, 18)); // NOI18N

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/todasRotas.jpg"))); // NOI18N

        descricaoProblema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricaoProblema.setText("<html>   <font size=\"6\"> <b><p align =\"center\"> - Problema do Transporte -  <p align =\"center\">Método de Aproximação de Vogel</b> </font>   </br> \n<font size=\"5\"> <br> A forja de armaduras \"Kovir&Poviss\" possui uma instalação matriz e uma filial. A primeira, F1, tem capacidade de produção total de <b>1800 </b> armaduras. Enquanto a filial, F2, um pouco menor, pode fornecer <b>700 </b> armaduras. </br> \n<br> <br> Kovir&Poviss distribui suas finais peças por 5 reinos da região: <b>R1, R2, R3, R4, e R5 </b>. A demanda de armaduras para os 5 reinos é fixa e distribuída conforme indicado abaixo, respectivamente: <b> 890, 105, 600, 405, 500</b>. </br> \n<br><br>  Os cavalos e embarcações disponíveis para fazer o transporte das mercadorias atendem a todas as rotas, entretanto, cada uma possui um custo variado. O custo de transporte deve ser fornecido. </br> \n<br> <br> O objetivo é atender a todos os reinos pelo menor custo de viagem. </br> \n");
        descricaoProblema.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));
        descricaoProblema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descricaoProblema.setMaximumSize(new java.awt.Dimension(650, 650));
        descricaoProblema.setPreferredSize(new java.awt.Dimension(600, 112));

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmarKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Inserir os dados: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descricaoProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(confirmar)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descricaoProblema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        TelaInserirPesosRotas panel = new TelaInserirPesosRotas();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_confirmarActionPerformed

    private void confirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_confirmarKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel descricaoProblema;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
