/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.Transporte;

/**
 *
 * @author Gabriel
 */
public class TelaResultado extends javax.swing.JFrame {

    private final ArrayList<Transporte> transportes;
    private final Integer estoqueFabricaUm;
    private final Integer estoqueFabricaDois;

    /**
     * Creates new form TelaResultado
     *
     * @param transportes
     * @param estoqueFabricaUm
     * @param estoqueFabricaDois
     */
    public TelaResultado(ArrayList<Transporte> transportes, Integer estoqueFabricaUm, Integer estoqueFabricaDois) {
        initComponents();
        this.transportes = transportes;
        this.estoqueFabricaDois = estoqueFabricaDois;
        this.estoqueFabricaUm = estoqueFabricaUm;
        Integer custoFinal = 0;
        String mensagem = "<html>"
                + "<head>\n"
                + "<style>\n"
                + "table {\n"
                + "    font-family: arial, sans-serif;\n"
                + "    border-collapse: collapse;\n"
                + "    width: 100%;\n"
                + "}\n"
                + "\n"
                + "td, th {\n"
                + "    border: 1px solid #dddddd;\n"
                + "    text-align: left;\n"
                + "    padding: 8px;\n"
                + "}\n"
                + "\n"
                + "tr:nth-child(even) {\n"
                + "    background-color: #dddddd;\n"
                + "}\n"
                + "</style>\n"
                + "</head>"
                + "<body>"
                + "<table>\n"
                + "  <tr>\n"
                + "    <th>Reino</th>\n"
                + "    <th>Quantidade Transportada</th>\n"
                + "    <th>Penalidade</th>\n"
                + "    <th>Custo Total</th>\n"
                + "  </tr>";

        for (Transporte transporte : transportes) {
            mensagem = mensagem.concat(
                    "<tr>"
                    + "<td>" + transporte.getNomeReino() + "</td>"
                    + "<td>" + transporte.getQuantidadeTransportada() + "</td>"
                    + "<td>" + transporte.getPenalidade() + "</td>"
                    + "<td>" + (transporte.getPenalidade() * transporte.getQuantidadeTransportada()) + "</td>"
                    + "</tr>"
            );
            custoFinal += transporte.getPenalidade() * transporte.getQuantidadeTransportada();
        }
        mensagem = mensagem.concat("<tr>\n"
                + "  <th colspan=\"3\" >Custo Final</th>"
                + "<td>" + custoFinal) + "</td>"
                + "</tr>"
                + "</table>"
                + "</body>"
                + "</html>";

        this.mensagemFinal.setContentType("text/html");
        this.mensagemFinal.setText(mensagem);
        //this.mensagemFinal.setText(String.valueOf(mensagem));

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensagemFinal = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Resultado Final");

        jScrollPane1.setViewportView(mensagemFinal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaResultado(new ArrayList(), 0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane mensagemFinal;
    // End of variables declaration//GEN-END:variables
}
