package view;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Társila
 */
public class TelaDescricaoProblema extends javax.swing.JFrame {

    public TelaDescricaoProblema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagem = new javax.swing.JLabel();
        descricaoProblema = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problema do Transporte");
        setFont(new java.awt.Font("Adobe Arabic", 0, 18)); // NOI18N

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/todasRotas.jpg"))); // NOI18N

        descricaoProblema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricaoProblema.setText("<html>\n\t\t<p align =\"center\"> <font size=\"6\">- Problema do Transporte - </font> </p>\n\t\t<p align =\"center\"> <font size=\"6\">Método de Aproximação de Vogel </font></p>\n\t\t <font size=\"5\"> \n\t\t <p align =\"justify\"> <br> A forja de armaduras \"Kovir&Poviss\" possui uma instalação matriz e uma filial. A primeira, F1, tem capacidade de produção total de\n\t\t <b>1800 </b> armaduras. Enquanto a filial, F2, um pouco menor, pode fornecer \n\t\t <b>700 </b> armaduras. </br>  \n\t\t <p align =\"justify\"> <br> Kovir&Poviss distribui suas peças por 5 reinos da região:\n\t\t <b>R1, R2, R3, R4, e R5 </b>. A demanda de armaduras para os 5 reinos é váriavel e fornecida pelos clientes \n\t\t de cada reino mensalmente.  \n\t\t <p align =\"justify\"> <br>  Os cavalos e embarcações disponíveis para fazer o transporte das mercadorias atendem a todas as rotas,\n\t\t entretanto, cada uma possui um custo variado. O custo de transporte deve ser fornecido. \n\t\t <p align =\"justify\"> <br> O objetivo é atender a todos os reinos pelo menor custo de viagem. </p></font>\n </html>");
        descricaoProblema.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));
        descricaoProblema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descricaoProblema.setMaximumSize(new java.awt.Dimension(650, 650));
        descricaoProblema.setPreferredSize(new java.awt.Dimension(600, 112));

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmarKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Inserir os dados: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmar)
                .addGap(255, 255, 255))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descricaoProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descricaoProblema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagem, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(confirmar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        TelaInserirPesosRotas panel = new TelaInserirPesosRotas();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_confirmarActionPerformed

    private void confirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_confirmarKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel descricaoProblema;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
