package view;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import model.CalculosVogel;
import model.Reino;

/**
 *
 * @author Gabriel
 */
public class TelaInserirPesosRotas extends javax.swing.JFrame {

    private static final Map<String, String> mapaCaminhoIcones = new HashMap<>();
    private final Map<String, Reino> mapaReinos = new HashMap<>();
    private final Reino reinoUm;
    private final Reino reinoDois;
    private final Reino reinoTres;
    private final Reino reinoQuatro;
    private final Reino reinoCinco;

    static {
        mapaCaminhoIcones.put("Reino 1", "/resources/R1rota.jpg");
        mapaCaminhoIcones.put("Reino 2", "/resources/R2rota.jpg");
        mapaCaminhoIcones.put("Reino 3", "/resources/R3rota.jpg");
        mapaCaminhoIcones.put("Reino 4", "/resources/R4rota.jpg");
        mapaCaminhoIcones.put("Reino 5", "/resources/R5rota.jpg");
    }

    private Reino getReino(String itemSelecionado) {
        if (mapaReinos.containsKey(itemSelecionado)) {
            return mapaReinos.get(itemSelecionado);
        }
        return null;
    }

    private static String getPath(String itemSelecionado) {
        if (mapaCaminhoIcones.containsKey(itemSelecionado)) {
            return mapaCaminhoIcones.get(itemSelecionado);
        }
        return null;
    }

    public TelaInserirPesosRotas() {
        initComponents();

        this.reinoUm = new Reino();
        this.reinoDois = new Reino();
        this.reinoTres = new Reino();
        this.reinoQuatro = new Reino();
        this.reinoCinco = new Reino();
        mapaReinos.put("Reino 1", this.reinoUm); //não inseri isso estatico, pois as variaveis são variaveis dã
        mapaReinos.put("Reino 2", this.reinoDois);
        mapaReinos.put("Reino 3", this.reinoTres);
        mapaReinos.put("Reino 4", this.reinoQuatro);
        mapaReinos.put("Reino 5", this.reinoCinco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        destino = new javax.swing.JComboBox();
        labelDestino = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelFabrica2 = new javax.swing.JLabel();
        cadastroValorRota = new javax.swing.JButton();
        rotaFabricaDois = new javax.swing.JTextField();
        rotaFabricaUm = new javax.swing.JTextField();
        lembrete = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        demandaReino = new javax.swing.JTextField();
        labelDemanda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        titulo.setText("Informe o Custo das Rotas e a Demanda ");

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/R1rota.jpg"))); // NOI18N

        destino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reino 1", "Reino 2", "Reino 3", "Reino 4", "Reino 5" }));
        destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoActionPerformed(evt);
            }
        });

        labelDestino.setText("Selecione o reino:");
        labelDestino.setNextFocusableComponent(destino);

        labelValor.setText("<html> <p>Informe o custo da viagens</p> <p>Fábrica 1:</p> </html>");

        labelFabrica2.setText("Fábrica 2:");

        cadastroValorRota.setText("Cadastrar");
        cadastroValorRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroValorRotaActionPerformed(evt);
            }
        });
        cadastroValorRota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroValorRotaKeyPressed(evt);
            }
        });

        lembrete.setText("<html> <p>*Lembre-se não faz sentido</p> <p>encomendar meia armadura,</p><p>logo a demanda é um inteiro</p>  </html>");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        calcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calcularKeyPressed(evt);
            }
        });

        labelDemanda.setText("Demanda do Reino:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDestino, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFabrica2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rotaFabricaUm, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rotaFabricaDois, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cadastroValorRota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(demandaReino, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lembrete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDemanda, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(labelDestino)
                        .addGap(13, 13, 13)
                        .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotaFabricaUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(labelFabrica2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rotaFabricaDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDemanda)
                        .addGap(18, 18, 18)
                        .addComponent(demandaReino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cadastroValorRota)
                        .addGap(18, 18, 18)
                        .addComponent(lembrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(calcular)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoActionPerformed
        String nomeReino = (String) this.destino.getSelectedItem();

        this.limpaInputs();
        this.alteraImagemMapa(nomeReino);
    }//GEN-LAST:event_destinoActionPerformed

    private void cadastroValorRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroValorRotaActionPerformed
        String nomeReino = (String) this.destino.getSelectedItem();
        Reino reinoSelecionado = getReino(nomeReino);
        reinoSelecionado.setNomeReino(nomeReino);
        setPesosRotas(reinoSelecionado);
        this.destino.requestFocus();
        this.limpaInputs();
    }//GEN-LAST:event_cadastroValorRotaActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        Integer dummy = 0;
        for (Map.Entry<String, Reino> entrySet : mapaReinos.entrySet()) {
            Reino value = entrySet.getValue();
            dummy += value.getDemanda();
        }
        chamadaMetodoVogel(dummy);
    }//GEN-LAST:event_calcularActionPerformed

    private void cadastroValorRotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroValorRotaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastroValorRota.doClick();
        }
    }//GEN-LAST:event_cadastroValorRotaKeyPressed

    private void calcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calcularKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calcular.doClick();
        }
    }//GEN-LAST:event_calcularKeyPressed

    private void chamadaMetodoVogel(Integer dummy) {
        CalculosVogel calculo = new CalculosVogel(mapaReinos);
        if (dummy > 2500) {
            this.calculaPenalidades(true);
            calculo.transformaMapaEmArrayComDummyOferta();
        }
        if (dummy < 2500) {
            this.calculaPenalidades(false);
            calculo.transformaMapaEmArrayComDummyDemanda();
        } else {
            this.calculaPenalidades(false);
            calculo.transformaMapaEmArraySemDummy();
        }
    }

    private void calculaPenalidades(boolean dummy) {
        if (!dummy) {
            for (Map.Entry<String, Reino> entrySet : mapaReinos.entrySet()) {
                Reino value = entrySet.getValue();
                value.setPenalidade();
            }
        } else {
            for (Map.Entry<String, Reino> entrySet : mapaReinos.entrySet()) {
                Reino value = entrySet.getValue();
                value.setPenalidadeDummy();
            }
        }
    }

    private void setPesosRotas(Reino reino) {
        reino.setRotaFabricaUm(Integer.parseInt(this.rotaFabricaUm.getText()));
        reino.setRotaFabricaDois(Integer.parseInt(this.rotaFabricaDois.getText()));
        reino.setDemanda(Integer.parseInt(this.demandaReino.getText()));
    }

    private void limpaInputs() {
        this.rotaFabricaUm.setText("");
        this.rotaFabricaDois.setText("");
        this.demandaReino.setText("");
    }

    private void alteraImagemMapa(String reino) {
        Icon novaImagem = new javax.swing.ImageIcon(getClass().getResource(getPath(reino)));
        this.imagem.setIcon(novaImagem);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInserirPesosRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInserirPesosRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInserirPesosRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInserirPesosRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInserirPesosRotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroValorRota;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField demandaReino;
    private javax.swing.JComboBox destino;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel labelDemanda;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelFabrica2;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel lembrete;
    private javax.swing.JTextField rotaFabricaDois;
    private javax.swing.JTextField rotaFabricaUm;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
